# Generated by Django 5.2.6 on 2025-10-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_familia',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_famillia',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
