# Generated by Django 5.2.7 on 2025-10-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_producto', '0002_remove_producto_id_familia_producto_id_famillia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_famillia',
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
